import * as images from "../../assets/project-img";


const {img1, img2, img3, img4, img5, img6, img7, img8, img9} = images;

const prod = [
    {
        id: 1,
        name: 'Portfolio',
        description: 'Designed and developed a clean and modern portfolio website for showcasing my projects and skills using HTML, CSS, and JavaScript. Utilized responsive design to ensure compatibility across all devices. And Deployed on GitHub pages via GitHub Actions.',
        src: img8,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "HTML - CSS - JAVASCRIPT - JQUERY - FIREBASE",
        code: "https://github.com/Witcher0766/portfolio",
        live: "https://witcher0766.github.io/portfolio/",
    },
    {
        id: 2,
        name: 'Countries Data',
        description: 'Designed and developed a webapp that fetch data from real time API. And display the useful information of the different country to the user.',
        src: img1,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS - API",
        code: "https://github.com/Witcher0766/countries__api",
        live: "https://country-api-c5eg.onrender.com/",
    },
    {
        id: 3,
        name: 'E-commerce',
        description: 'Design and developed a responsive fully functional ecommerce website with admin feature and used stripe for the payment. Utilized responsive design to ensure compatibility across all devices.',
        src: img3,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS - REDUX - FIREBASE - FIRESTORE - STRIPE",
        code: "https://github.com/Witcher0766/eCom",
        live: "https://ecom-73tg.onrender.com/",
    },
    {
        id: 4,
        name: 'YouTube Clone',
        description: 'Tried to make a youtube clone, that contain some of the functionality of youtube by using a real time API.',
        src: img2,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS - MATERIALUI - API",
        code: "https://github.com/Witcher0766/youtube__clone",
        live: "https://youtube-clone-i2xz.onrender.com/",
    },
    {
        id: 5,
        name: 'Todo Webapp',
        description: 'A CRUD application exposed using reactjs and localstorag.',
        src: img6,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS - LOCALSTORAGE",
        code: "https://github.com/Witcher0766/reactTodo",
        live: "https://witcher0766.github.io/reactTodo/",
    },
    {
        id: 6,
        name: 'Weather Webapp',
        description: 'Designed and developed a webapp that fetch data from real time API. And display the useful information about weather of the different places to the user.',
        src: img7,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS - API",
        code: "https://github.com/Witcher0766/React_Weather_Site",
        live: "https://witcher0766.github.io/React_Weather_Site/",
    },
    {
        id: 7,
        name: 'Tic-Tac-Toe',
        description: 'Created a popular game Tic-Tac-Toe with attractive UI.',
        src: img9,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS",
        code: "https://github.com/Witcher0766/Tic-Tac-Toe",
        live: "https://witcher0766.github.io/Tic-Tac-Toe/",
    },
    {
        id: 8,
        name: 'Huddle Landing Page',
        description: 'Developed a landing page.',
        src: img4,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "REACTJS",
        code: "https://github.com/Witcher0766/react-landing-page",
        live: "https://witcher0766.github.io/react-landing-page/",
    },
    {
        id: 9,
        name: 'SunnySide Landing Page',
        description: 'Developed a sunnyside landing page.',
        src: img5,
        btn1: "Code",
        btn2: "Live Demo",
        tech: "HTML - CSS - JAVASCRIPT",
        code: "https://github.com/Witcher0766/resfrontenedwebpage",
        live: "https://witcher0766.github.io/resfrontenedwebpage/",
    },

]

export default prod;